const Sequelize=require("sequelize");
//const sequelize=require("../database/connection");
module.exports=sequelize.define("member",{
    member_id:{
        type:Sequelize.BIGINT,
        allowNull:false,
        autoIncrement:true,
        primaryKey:true
    },
    first_name:{
        type:Sequelize.STRING(60),
        allowNull:false
    },
    last_name:{
        type:Sequelize.STRING(60),
        allowNull:false
    },
    gender:{
        type:Sequelize.STRING(6),
        allowNull:false
    },
    email:{
        type:Sequelize.STRING(100),
        allowNull:false,
        unique:true
    },
    user_type:{
        type:Sequelize.STRING(10),
        allowNull:false
    },
    password:{
        type:Sequelize.STRING(255),
        allowNull:false
    },
});