const Sequelize=require("sequelize");
module.exports=sequelize.define("Member",{
    member_id:{
        type:Sequelize.BIGINT,
        allowNull:false,
        autoIncrement:true,
        primaryKey:true
    },
    first_name:{
        type:Sequelize.STRING(60),
        allowNull:false
    },
    last_name:{
        type:Sequelize.STRING(60),
        allowNull:false
    },
    email:{
        type:Sequelize.STRING(100),
        allowNull:false,
        unique:true
    },
});